### ISSUE TITLE
sub_domains is counterintuitive

### ISSUE THREAD

**Issue by anis-campos** [ms-jpq/simple-traefik-identity#3]
Issue
---

`sub_domains`, for me, looks like a list of sud domains, i.e., the part before the domain. 

so let's say I have 3 domains `a.com`,`b.com` and `c.com`, I was expecting to enable `sonarr` over those three domaines with:
``` yaml
  groups:
    - name: all
      sub_domains:
        - "*"
    - name: sonarr
      sub_domains:
        - sonarr
```

But for what I understand, we need to set each and every one of the FQDNs in, like so:
```yaml
    - name: sonarr
      sub_domains:
        - sonarr.a.com
        - sonarr.b.com
        - sonarr.c.com
```
And this for every `sub domain`. That is most of the times ok, but what if I want to have a user with access over 10 sub domains, it really starts to be cumbersome.

Solution
---

`sub_domains` should just be a list of sub domains, de facto enabling the access over all the domains. 

One might ask for a way to also restrict to one or more  domains. This could simply be a field `domains` in `group` to restrict this group to a given list of domains.
